update activecalls set lega_codec='allow' where id=1;
update activecalls set lega_codec='dissallow' where id=3;
update activecalls set lega_codec='allow' where id=12;
update activecalls set lega_codec='dissallow' where id=17;
update activecalls set lega_codec='allow' where id=4;
update activecalls set legb_codec='g443' where id=1;
update activecalls set legb_codec='sd44' where id=3;
update activecalls set legb_codec='e442' where id=12;
update activecalls set legb_codec='d729' where id=17;
update activecalls set legb_codec='a566' where id=4;
update activecalls set pdd=0.045 where id=16;
update activecalls set pdd=0.45 where id=1;
update activecalls set pdd=0.233 where id=3;
update activecalls set pdd=2.44 where id=12;
update activecalls set pdd=444 where id=17;
update activecalls set pdd=2.23 where id=4;
delete from activecalls where id!=1 and id!=4 and id!=16 and id!=17;
