update users set balance=60 where id=0;
update users set currency_id=44 where id=0;
update users set balance=26 where id=2;
update users set currency_id=42 where id=2;  
update users set balance=36 where id=3;
update users set currency_id=34 where id=3;  
update users set balance=44 where id=4;
update users set currency_id=2 where id=4;
update currencies set active =1 where id=44;
update currencies set active =1 where id=42;
update currencies set active =1 where id=34;
update tariffs set currency ='CRC' where id = 9;
update tariffs set currency ='EGP' where id = 14;
update tariffs set currency ='EUR' where id = 11;
update tariffs set currency ='NLG' where id = 10;
update tariffs set currency ='CRC' where id = 6;
update tariffs set currency ='EGP' where id = 15;
update tariffs set currency ='NLG' where id = 8;
update tariffs set currency ='CRC' where id = 22;
update tariffs set currency ='EGP' where id = 23;
update tariffs set currency ='CRC' where id = 21;
update tariffs set currency ='NLG' where id = 18;
