INSERT INTO `cron_settings`(`id`,`action`                ,`user_id`,`name`      ,`description` ,`target_id`,`target_class`,`to_target_id`,`to_target_class`,`periodic_type`,`to_do_time`,`repeat_forever`,`priority`,`to_do_times`,`valid_from`                   ,`valid_till`                   ,`created_at`                   ,`updated_at`                  , `provider_target_id` , `provider_to_target_id`,`lcr_id`)
VALUES                     (121 ,'change_tariff'         ,0        ,'Geras '    ,'Apibudinimas',2          ,'User'        ,4             ,'Tariff'         ,0              ,NULL        ,0               ,0         ,NULL         ,subdate(now(), interval 3 hour),adddate(now(), interval 3 hour),subdate(now(), interval 4 hour),subdate(now(), interval 4 hour),NULL,NULL,NULL),
                           (122 ,'change_tariff'         ,0        ,'Geriau'    ,'Apibudinimas',3          ,'User'        ,2             ,'Tariff'         ,0              ,NULL        ,0               ,0         ,NULL         ,subdate(now(), interval 3 hour),adddate(now(), interval 3 hour),subdate(now(), interval 4 hour),subdate(now(), interval 4 hour),NULL,NULL,NULL),
                           (123 ,'change_tariff'         ,0        ,'Gerai '    ,'Apibudinimas',4          ,'User'        ,4             ,'Tariff'         ,0              ,NULL        ,0               ,0         ,NULL         ,subdate(now(), interval 3 hour),adddate(now(), interval 3 hour),subdate(now(), interval 4 hour),subdate(now(), interval 4 hour),NULL,NULL,NULL),
                           (124 ,'change_provider_tariff',0        ,'Name'      ,'Apibudinimas',-1         ,'Provider'    ,4             ,'Provider_Tariff',0              ,NULL        ,0               ,0         ,NULL         ,subdate(now(), interval 3 hour),adddate(now(), interval 3 hour),subdate(now(), interval 4 hour),subdate(now(), interval 4 hour),1,5,NULL),
                           (125 ,'change_LCR'            ,0        ,'LCR change','Apibudinimas',2          ,'User'        ,4             ,'User_LCR'       ,0              ,NULL        ,0               ,0         ,NULL         ,subdate(now(), interval 3 hour),adddate(now(), interval 3 hour),subdate(now(), interval 4 hour),subdate(now(), interval 4 hour),NULL,NULL,3);
INSERT INTO `cron_actions` (`id`,`cron_setting_id`,`attempts`,`locked_by`,`last_error`,`handler`,`run_at`                       ,`locked_at`,`failed_at`,`created_at`                   ,`updated_at`)
VALUES                     ( 11 ,121              ,0         ,NULL       ,NULL        ,NULL     ,subdate(now(), interval 1 hour),NULL       ,NULL       ,subdate(now(), interval 2 hour),subdate(now(), interval 2 hour)),
                           ( 12 ,122              ,0         ,NULL       ,NULL        ,NULL     ,subdate(now(), interval 1 hour),NULL       ,NULL       ,subdate(now(), interval 2 hour),subdate(now(), interval 2 hour)),
                           ( 13 ,123              ,0         ,NULL       ,NULL        ,NULL     ,subdate(now(), interval 1 hour),NULL       ,NULL       ,subdate(now(), interval 2 hour),subdate(now(), interval 2 hour)),
                           ( 14 ,124              ,0         ,NULL       ,NULL        ,NULL     ,subdate(now(), interval 1 hour),NULL       ,NULL       ,subdate(now(), interval 2 hour),subdate(now(), interval 2 hour)),
                           ( 15 ,125              ,0         ,NULL       ,NULL        ,NULL     ,subdate(now(), interval 1 hour),NULL       ,NULL       ,subdate(now(), interval 2 hour),subdate(now(), interval 2 hour));
