ssl: true
test:
  :server: "pop.gmail.com"
  :username: "kolmitest@gmail.com"
  :password: "kolmitest99"
development:
  :server: "imap.gmail.com"
  :port: 993
  :username: "kolmitest@gmail.com"
  :password: "kolmitest99"
